// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfSoYhmI9FOdi0Jcv60zydtl9FInfsmZc',
    appId: '1:557594002629:web:2cc5be7ada78c51a7e1cac',
    messagingSenderId: '557594002629',
    projectId: 'arikkari-927c7',
    authDomain: 'arikkari-927c7.firebaseapp.com',
    storageBucket: 'arikkari-927c7.appspot.com',
    measurementId: 'G-S3PDNYSHDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk9nRs6uUnPueoeqsCO24DREanHGyL4OE',
    appId: '1:557594002629:android:e418fe9fde0352777e1cac',
    messagingSenderId: '557594002629',
    projectId: 'arikkari-927c7',
    storageBucket: 'arikkari-927c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6gUGcCWE9B2_5Zm1OyTJLKqYPgLV-jJ4',
    appId: '1:557594002629:ios:3f556a84ccbcb40e7e1cac',
    messagingSenderId: '557594002629',
    projectId: 'arikkari-927c7',
    storageBucket: 'arikkari-927c7.appspot.com',
    androidClientId: '557594002629-iou2mts6r9vld1u8r26370c63v56bmsl.apps.googleusercontent.com',
    iosClientId: '557594002629-mbd45galnmeil5k7uaqbp9b1qu625dvo.apps.googleusercontent.com',
    iosBundleId: 'com.daon.flutterProject',
  );
}
